## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------
title = "xMAGNET Simulations"
copyright = "{year}"
theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "false"

# Local
baseURL = "https://xmagnet-simulations.github.io/"
publishDir = "public"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]

[Params.social]