## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "xMAGNET Simulations"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "false"

# Remote
baseURL = "https://xmagnet-simulations.github.io/"
publishDir = "public"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "The xMAGNET AGN Simulations"
  favicon = false

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]
